[WsServer]
Addr = "0.0.0.0"
Port = 8080
JwtSecret = "secret"
ID = "node1"

[MySql]
Host = "dengzii.com"
Port = 3306
Username = "go_im_test"
Password = ""
Db = "go_im_test"
Charset = "utf8mb4"

[Redis]
Host = "dengzii.com"
Port = 6378
Password = ""
Db = 9