[ApiHttp]
Addr = "0.0.0.0"
Port = 8081

[WsServer]
Addr = "0.0.0.0"
Port = 8080

[IMRpcServer]
EnableGroup = false
Addr = "0.0.0.0"
Port = 8092
Network = "tcp"
Etcd = []
Name = "im_rpc_server"

[MySql]
Host = "dengzii.com"
Port = 3306
Username = "go_im_test"
Password = "8dmaRNCYBFHP4F67"
Db = "go_im_test"
Charset = "utf8mb4"

[Redis]
Host = "dengzii.com"
Port = 6378
Password = "tcmm1713."
Db = 9